version: '3.8'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    environment:
      PUID: 1000
      PGIN: 1000
    ports:
      - '443:443'
      - '80:80'
      - '81:81'
    dns:
      - '8.8.8.8'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    healthcheck:
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s

networks:
  nginx_default:
    name: nginx_default
    external: true
